#!/usr/bin/env php
<?php declare(strict_types=1);

// @todo: remove analytics and other garbage files before zipping
// @todo: show a help screen...?
// @todo: show a splash screen

if (!isset($argv[1])) {
    exit(1);
}

// Gather current working directory so that finished file can be moved back to this location
$d = getcwd();

// Scrub the URL given on the command line so that it may be used when saving the final zip name
$scrubbed = preg_replace("/[^A-Za-z0-9.]/", '', $argv[1]);

// Create a timestamp in the format of YYYYMMDDHHII
$time = date('Ymdhi');

// Create a temp directory
`mkdir /tmp/$scrubbed`;

// Run the wget command to archive all elements of the page and store in the temp folder
`cd /tmp/$scrubbed ; wget --recursive --html-extension --convert-links --restrict-file-names=windows --no-parent --no-directories --level=1 --span-hosts $argv[1]`;

// Use p7zip to zip the temp folder with its contents
`7z a -mx9 /tmp/$scrubbed.$time.7z /tmp/$scrubbed/*`;

// Remove the temp folder
`rm -rfv /tmp/$scrubbed`;

// Move the zip into the current working directory
`mv /tmp/$scrubbed.$time.7z $d`;
